- name: install nginx
  dnf:
    name: nginx
    state: installed

- name: start and enable nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: run app-pre-requisites
  import_role: # this will import roles
    name: common # from common folder
    tasks_from: app-pre-req # in common folder task from app-pre-req folder

- name: copy expense content
  template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify: # if you use handlers if any modification in configuration file then nginx restart will happen otherwise it will nor restart
  - restart nginx

# - name: restart nginx
#   service:
#     name: nginx
#     state: restarted